global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
            - targets: ['collectdhost-first.example.com:8443']
    scheme: https
    tls_config:
        ca_file: /etc/prometheus/keys/myrootCA.crt
        cert_file: /etc/prometheus/keys/client-certificate.crt
        key_file:  /etc/prometheus/keys/client.key
        server_name: collectdhost-first.example.com
