global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
            - targets: ['collectdhost-first.hpvsmonitor.com:8443']
    scheme: https
    tls_config:
        ca_file: /etc/prometheus/keys/servercertificate.pem
        cert_file: /etc/prometheus/keys/clientcertificate.pem
        key_file:  /etc/prometheus/keys/client.key
        server_name: collectdhost-first.hpvsmonitor.com
